dove run <call> or dove tx <call>: hints changed
pontem-network/move-tools pull request #96
Opened 2021-07-23 07:52 UTC by vladimirovmm

2021-08-02 14:50 UTC, mkurnikov requested changes

2021-08-02 14:50 UTC, mkurnikov commented on dove/tests/test_cmd_dove_tx.rs
> +/// $ dove tx sdemo_4<u8>(16)
@vladimirovmm Could you add test for multiple parameters of the script? I'm not sure it's going to work without quotes

2021-08-02 17:54 UTC, fzzr- commented on dove/src/transaction.rs
> +            anyhow::bail!("{}", &error_message);
I'm not sure but is there `"Invalid arguments format"` message missed?

2021-08-02 17:57 UTC, fzzr- commented on dove/src/transaction.rs
> +        lexer.advance().map_err(|_| anyhow!("{}", &error_message))?;
Why don't we just use single closure instead of various four?

2021-08-03 07:56 UTC, fzzr- requested changes
Increment of Patch part of Dove version is missed.

2021-08-03 12:33 UTC, fzzr- approved these changes

2021-08-03 13:48 UTC, merged